<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1n6P8pO' shared service.

return $this->privates['.service_locator.1n6P8pO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService.php', true],
], [
    'logger' => '?',
]);
