<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cUaaTxr' shared service.

return $this->privates['.service_locator.cUaaTxr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ArticleController::show' => ['privates', '.service_locator.ah46ZAc', 'get_ServiceLocator_Ah46ZAcService.php', true],
    'App\\Controller\\ArticleController::toggleArticleHeart' => ['privates', '.service_locator.1n6P8pO', 'get_ServiceLocator_1n6P8pOService.php', true],
    'App\\Controller\\ArticleController:show' => ['privates', '.service_locator.ah46ZAc', 'get_ServiceLocator_Ah46ZAcService.php', true],
    'App\\Controller\\ArticleController:toggleArticleHeart' => ['privates', '.service_locator.1n6P8pO', 'get_ServiceLocator_1n6P8pOService.php', true],
], [
    'App\\Controller\\ArticleController::show' => '?',
    'App\\Controller\\ArticleController::toggleArticleHeart' => '?',
    'App\\Controller\\ArticleController:show' => '?',
    'App\\Controller\\ArticleController:toggleArticleHeart' => '?',
]);
