<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'monolog.handler.markdown_logging' shared service.

$this->privates['monolog.handler.markdown_logging'] = $instance = new \Monolog\Handler\StreamHandler(($this->targetDirs[2].'/log/markdown.log'), 100, true, NULL, false);

$instance->pushProcessor(($this->privates['monolog.processor.psr_log_message'] ?? ($this->privates['monolog.processor.psr_log_message'] = new \Monolog\Processor\PsrLogMessageProcessor())));

return $instance;
