<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ah46ZAc' shared service.

return $this->privates['.service_locator.ah46ZAc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cache' => ['services', 'cache.app', 'getCache_AppService', false],
    'markdown' => ['services', 'markdown.parser', 'getMarkdown_ParserService', false],
    'markdownHelper' => ['privates', 'App\\Service\\MarkdownHelper', 'getMarkdownHelperService.php', true],
], [
    'cache' => '?',
    'markdown' => '?',
    'markdownHelper' => 'App\\Service\\MarkdownHelper',
]);
