<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX7i9ybo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX7i9ybo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX7i9ybo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX7i9ybo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX7i9ybo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X7i9ybo',
    'container.build_id' => '4846ab94',
    'container.build_time' => 1574336602,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX7i9ybo');
