<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ2v6eA5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ2v6eA5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ2v6eA5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ2v6eA5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJ2v6eA5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'J2v6eA5',
    'container.build_id' => '9f8fe873',
    'container.build_time' => 1574314747,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ2v6eA5');
